---
clickhouse:
  hosts:
    clickhouse-01:
      ansible_host: 51.250.14.52


vector:
  hosts:
    vector-01:
      ansible_host: 51.250.14.52

lighthouse:
  hosts:
    lighthouse-01:
      ansible_host: 51.250.14.52



